### ISSUE TITLE
make runtest error

### ISSUE THREAD

**Issue by markzampoglou** [kevinlin311tw/caffe-augmentation#2]
Hello, and thank you for providing this code.

I have configured and built the project but I am getting the following error in make runtest:

```
[----------] 4 tests from ImageDataLayerTest/2, where TypeParam = caffe::GPUDevice<float>
[ RUN      ] ImageDataLayerTest/2.TestResize
F0419 17:37:02.960711 23471 data_transformer.cpp:780] Check failed: rng_ 
*** Check failure stack trace: ***
    @     0x2b9b19650daa  (unknown)
    @     0x2b9b19650ce4  (unknown)
    @     0x2b9b196506e6  (unknown)
    @     0x2b9b19653687  (unknown)
    @     0x2b9b1ae1d463  caffe::DataTransformer<>::Rand()
    @     0x2b9b1ae22c9e  caffe::DataTransformer<>::Transform()
    @     0x2b9b1ad8659a  caffe::ImageDataLayer<>::load_batch()
    @     0x2b9b1adbc539  caffe::BasePrefetchingDataLayer<>::InternalThreadEntry()
    @     0x2b9b1ae2a180  caffe::InternalThread::entry()
    @     0x2b9b230d6a4a  (unknown)
    @     0x2b9b1b87a182  start_thread
    @     0x2b9b1bb8a47d  (unknown)
    @              (nil)  (unknown)
make: *** [runtest] Aborted (core dumped)
```

I am not sure which version of caffe this branch is based on -I am compiling on CUDNN v3 and CUDA 7.0, used for older branches -the build process seems to work fine in this regard.

Thank you very much in any case.

**Comment by kevinlin311tw** [comment]
I think you could ignore this error because I didn't write the testing code for runtest.

**Comment by markzampoglou** [comment]
You are right, the binaries run fine. Thank you very much for the help!

**Comment by kevinlin311tw** [comment]
BTW, the augmentation function is only supported in train phase. I will extend this to test phase in future!
